spring:
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch_job_repository
    username: root
logging:
  level:
    root: WARN
    org.springframework.batch: WARN
